networks:
  net:
    driver: bridge

services:
  ############################################# Visualization ################################################
  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    volumes:
      - ./visualization/grafana/provisioning:/etc/grafana/provisioning
      - ./data/grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - net
    labels:
      org.label-schema.group: 'observability'
    user: root

  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: alertmanager
    volumes:
      - ./visualization/alertmanager/config:/etc/alertmanager/config
      - ./data/alertmanager:/tmp/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config/config.yaml'
      - '--storage.path=/tmp/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - net
    labels:
      org.label-schema.group: 'observability'
    user: root

  ############################################ Metrics #######################################################
#  prometheus:
#    image: prom/prometheus:v2.49.1
#    container_name: prometheus
#    expose:
#      - 9090
#    networks:
#      - net
#    volumes:
#      - ./metrics/prometheus:/etc/prometheus
#      - ./data/prometheus:/tmp/prometheus
#    command:
#      - '--config.file=/etc/prometheus/config/prometheus.yml'
#      - '--storage.tsdb.path=/tmp/prometheus'
#      - '--storage.tsdb.retention.time=200h'
#      - '--web.console.libraries=/etc/prometheus/console_libraries'
#      - '--web.console.templates=/etc/prometheus/consoles'
#      - '--web.enable-remote-write-receiver'
#      - '--web.enable-lifecycle'
#    restart: unless-stopped
#    labels:
#      org.label-schema.group: 'observability'
#    extra_hosts:
#      - "host.docker.internal: 172.17.0.1"
#    user: root

  mimir:
    image: grafana/mimir:2.12.0
    container_name: mimir
    expose:
      - 9009
    networks:
        - net
    volumes:
      - ./metrics/mimir/config:/etc/mimir/config
      - ./data/mimir:/tmp/mimir
    command:
      - '-config.file=/etc/mimir/config/mimir.yml'
    restart: unless-stopped
    labels:
      org.label-schema.group: 'observability'
    extra_hosts:
      - "host.docker.internal: 172.17.0.1"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.44.0
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - net
    labels:
      org.label-schema.group: 'observability'

  pushgateway:
    image: prom/pushgateway:v1.4.3
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - net
    labels:
      org.label-schema.group: 'observability'

  nodeexporter:
    image: prom/node-exporter:v1.3.1
    container_name: nodeexporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - net
    labels:
      org.label-schema.group: 'observability'

  nginxexporter:
    image: nginx/nginx-prometheus-exporter:0.10
    container_name: nginx-exporter
    expose:
      - 9113
    command:
      - -nginx.scrape-uri
      - http://nginx:8081/stub_status
    restart: unless-stopped
    networks:
      - net
    depends_on:
      nginx:
        condition: service_started
    labels:
      org.label-schema.group: 'observability'

  ############################################ Logging #######################################################
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    privileged: true
    user: root
    volumes:
      - ./logs/loki:/etc/loki
      - ./data/loki:/tmp/loki
    command:
      - '-config.file=/etc/loki/config/loki-config.yaml'
    restart: always
    expose:
      - 3100
    networks:
      - net
    labels:
      org.label-schema.group: 'observability'

#  syslog-ng:
#    image: linuxserver/syslog-ng:4.5.0
#    container_name: syslog-ng
#    user: root
#    privileged: true
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Etc/UTC
#    volumes:
#      - ./logs/syslog/config:/config
#      - /var/log:/var/log
#    networks:
#      - net
#    ports:
#      - 514:5514/udp
#      - 601:6601/tcp
#      - 6514:6514/tcp
#    restart: always
#    labels:
#      org.label-schema.group: 'observability'

  ############################################ Traces ########################################################
  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    privileged: true
    user: root
    volumes:
      - ./traces/tempo:/etc/tempo
      - ./data/tempo:/tmp/tempo
    command:
      - "-config.file=/etc/tempo/config/tempo.yaml"
    restart: always
    expose:
      - 3200   # tempo
      - 4318   # otlp http
    networks:
      - net
    labels:
      org.label-schema.group: 'observability'

  ############################################ Aggregation ###################################################
  alloy:
    image: grafana/alloy:v1.0.0
    user: root
    privileged: true
    container_name: alloy
    volumes:
      - ./aggregation/alloy/config:/etc/alloy
      - ./data/alloy:/tmp/alloy
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
    expose:
      - 12345 # dashboard port
      - 51893 # syslog
      - 4318  # oltp http
      - 8027  # app receiver
      - 9999  # logs http
    networks:
      - net
    restart: unless-stopped
    labels:
      org.label-schema.group: 'observability'

  ############################################# Network #######################################################
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    expose:
      - 8081 # nodexexporter
    ports:
      # grafana
      - protocol: tcp
        published: 5000
        target: 5000
      # alloy loki receiver
      - protocol: tcp
        published: 9999
        target: 9999
      # alloy oltp http
      - protocol: tcp
        published: 4318
        target: 4318
      # alloy app receiver
      - protocol: tcp
        published: 8027
        target: 8027
    volumes:
      - ./server/nginx:/etc/nginx
    networks:
      - net
    restart: unless-stopped
    labels:
      org.label-schema.group: 'server'

