{
 "title": "Pulse Observability",
 "description": "Telemetry FastAPI application with three pillars of observability: Traces (Tempo), Metrics (Prometheus), Logs (Loki) on Grafana through OpenTelemetry and OpenMetrics.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulse_http_requests_total{handler!=\"/metrics\", handler!=\"none\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pulse_http_requests_total{handler!=\"/metrics\", handler!=\"none\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pulse_http_request_duration_seconds_sum{handler!=\"none\", handler!=\"/metrics\"} / pulse_http_request_duration_seconds_count",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pulse_http_requests_total{status=\"5xx\"}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (pulse_http_requests_total{status=\"2xx\", handler!=\"/metrics\", handler!=\"none\"}) / sum by(handler) (pulse_http_requests_total{handler!=\"/metrics\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (pulse_http_requests_total{status=\"5xx\", handler!=\"/metrics\"}) / sum by(handler) (pulse_http_requests_total{ handler!=\"/metrics\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(handler, le) (rate(pulse_http_request_duration_seconds_bucket{handler!=\"/metrics\", handler!=\"none\"}[1m])))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Request In Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    { "expr": "progress", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(pulse_http_requests_total{handler!=\"/metrics\", handler!=\"none\"}[1m])",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(level) (rate({logger=~\"Pulse: production\"} [1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Log of All FastAPI App",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "{logger=~\"Pulse: production\"} | json | line_format `{{.event}}` |= `Request:`"
    }
   ]
  }
 ]
}