global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'docker-host-alpha'

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      follow_redirects: true
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: [ 'alertmanager:9093' ]